/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao_controle;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import modelo.Pessoa;

import modelo.dao.CadastrarPessoaDAO;

/**
 *
 * @author suporte
 */
public class PesquisaPessoas extends javax.swing.JFrame {

    private MaskFormatter CNPJMask;
    private MaskFormatter CPFMask;

    int aumentar = 0;
    private ArrayList<Pessoa> pessoasPesquisadas;

    /**
     * Creates new form PesquisaPessoas
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public PesquisaPessoas() throws Exception {
        initComponents();
            
    setResizable(false);
        rodarPesquisa();
        

    }

    public void jListaAtendimento() {
        jListaAtendimento.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        //  jListaAtendimento.getTableHeader().setBackground(new Color(32,136,203));
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.YELLOW);

        for (int i = 0; i < jListaAtendimento.getModel().getColumnCount(); i++) {
            jListaAtendimento.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }

    }

    public void rodarPesquisa() throws Exception {
       
        revalidate();
        CadastrarPessoaDAO dao = new CadastrarPessoaDAO();

        this.pessoasPesquisadas = dao.pesquisa(jPesquisarPessoa.getText());

        try {

            DefaultTableModel modeloTabela = (DefaultTableModel) jListaAtendimento.getModel();
            jListaAtendimento.getTableHeader().setEnabled(false);
            
            modeloTabela.setNumRows(0); //Limpa a tabela
            if (this.jPesquisarPessoa != null) {
                for (Pessoa p : this.pessoasPesquisadas) {
                    Object[] linha = new Object[5];
                    linha[0] = p.getNome();
                    linha[1] = p.getCpf_cnpj();
                    linha[2] = p.getTelefone();
                    linha[3] = new SimpleDateFormat("dd/MM/yyyy").format(p.getReclamacao().getData_reclamacao());
                    linha[4] = p.getReclamacao().getDescricao();
                    modeloTabela.addRow(linha);

                }
                if (modeloTabela.getRowCount() > 50) {

                    modeloTabela.setNumRows(50);

                }

            }
           

        } catch (Exception ex) {

            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar no banco de dados");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPesquisarPessoa = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaAtendimento = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCadastroReclamacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBackground(new java.awt.Color(224, 224, 226));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(1300, 730));

        jPanel2.setBackground(new java.awt.Color(224, 224, 226));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_pesquisar(2).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPesquisarPessoa.setBackground(new java.awt.Color(242, 242, 242));
        jPesquisarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisarPessoaActionPerformed(evt);
            }
        });
        jPesquisarPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPesquisarPessoaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPesquisarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPesquisarPessoa))
                .addContainerGap())
        );

        jListaAtendimento.setAutoCreateRowSorter(true);
        jListaAtendimento.setBackground(new java.awt.Color(224, 224, 226));
        jListaAtendimento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jListaAtendimento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jListaAtendimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF / CNPJ", "Telefone", "Data do Atendimento", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jListaAtendimento.setGridColor(new java.awt.Color(153, 153, 153));
        jListaAtendimento.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jListaAtendimento.setName(""); // NOI18N
        jListaAtendimento.setRequestFocusEnabled(false);
        jListaAtendimento.setRowHeight(20);
        jListaAtendimento.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jListaAtendimento.setShowVerticalLines(false);
        jListaAtendimento.getTableHeader().setReorderingAllowed(false);
        jListaAtendimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaAtendimentoMouseClicked(evt);
            }
        });
        jListaAtendimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jListaAtendimentoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jListaAtendimento);

        jPanel4.setBackground(new java.awt.Color(37, 170, 253));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        btnCadastroReclamacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icones/cadr.png"))); // NOI18N
        btnCadastroReclamacao.setToolTipText("");
        btnCadastroReclamacao.setPreferredSize(new java.awt.Dimension(117, 33));
        btnCadastroReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroReclamacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                        .addComponent(btnCadastroReclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastroReclamacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListaAtendimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListaAtendimentoKeyPressed
        try {
            // TODO add your handling code here:

        } catch (Exception ex) {
            Logger.getLogger(PesquisaPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jListaAtendimentoKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            rodarPesquisa();
            if (this.pessoasPesquisadas.isEmpty()) {

                String mensagem = "Pessoa não encontrada";
                JOptionPane optionPane = new JOptionPane();
                optionPane.setMessage(mensagem);
                optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
                JDialog dialog = optionPane.createDialog(null, "ATENÇÃO");
                dialog.setVisible(true);
                jPesquisarPessoa.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(PesquisaPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jListaAtendimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaAtendimentoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {

            int linhaSelecionada = jListaAtendimento.getSelectedRow();

            Pessoa pessoaSelecionada = this.pessoasPesquisadas.get(linhaSelecionada);

            try {
                ReclamacaoCompleta telaReclamacaoCompleta = new ReclamacaoCompleta();
                telaReclamacaoCompleta.setPessoaEmEdicao(pessoaSelecionada);
                telaReclamacaoCompleta.setVisible(true);
                rodarPesquisa(); //Atuaizar a lista após cadastro/alteraçao
                dispose();
            } catch (Exception ex) {
                Logger.getLogger(PesquisaPessoas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jListaAtendimentoMouseClicked

    private void jPesquisarPessoaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPesquisarPessoaKeyPressed
        try {
            // TODO add your handling code here:
         

        } catch (Exception ex) {

            String mensagem = "Pessoa não encontrada";
            JOptionPane optionPane = new JOptionPane();
            optionPane.setMessage(mensagem);
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog = optionPane.createDialog(null, "ATENÇÃO");
            dialog.setVisible(true);

        }

    }//GEN-LAST:event_jPesquisarPessoaKeyPressed

    private void btnCadastroReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroReclamacaoActionPerformed
        // TODO add your handling code here:
        CadPessoa telaCadastroPessoa = new CadPessoa();
        telaCadastroPessoa.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCadastroReclamacaoActionPerformed

    private void jPesquisarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisarPessoaActionPerformed
        try {

            // TODO add your handling code here:
            rodarPesquisa();
        } catch (Exception ex) {
            Logger.getLogger(PesquisaPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jPesquisarPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {

                    new PesquisaPessoas().setVisible(true);

                } catch (Exception ex) {
                    Logger.getLogger(PesquisaPessoas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroReclamacao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jListaAtendimento;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JFormattedTextField jPesquisarPessoa;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
