/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao_controle;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import modelo.Pessoa;
import modelo.Reclamacao;
import modelo.dao.CadastrarPessoaDAO;

/**
 *
 * @author suporte
 */
public class ReclamacaoCompleta extends javax.swing.JFrame {
     private Pessoa pessoaEmEdicao;
       private MaskFormatter CNPJMask;
    private MaskFormatter CPFMask;
    private MaskFormatter celularMask;
    private MaskFormatter fixoMask;
   

   
    /**
     * Creates new form ReclamacaoCompleta
     */
    public ReclamacaoCompleta() throws ParseException {
        
        initComponents();
          escolhaTelefone();
        setResizable(false);
        escolhaCPFouCNPJ();
      
     
      
       
    }
     

    public void setPessoaEmEdicao(Pessoa pessoaEmEdicao) throws ParseException {
    this.pessoaEmEdicao = pessoaEmEdicao;
     jVar.setText(String.valueOf(pessoaEmEdicao.getId()));
     idReclama.setText(String.valueOf(pessoaEmEdicao.getReclamacao().getId()));
     jNome.setText(pessoaEmEdicao.getNome());
     jTelefone.setText(pessoaEmEdicao.getTelefone());
     jCpf_Cnpj.setText(pessoaEmEdicao.getCpf_cnpj());
     jCalendario.setDate(pessoaEmEdicao.getReclamacao().getData_reclamacao());
     jDescricao.setText(pessoaEmEdicao.getReclamacao().getDescricao());

    }
    
     private Pessoa pessoaEditada = new Pessoa();
     private Reclamacao reclamacaoEditada = new Reclamacao();
   
    public void pegarInfoTela() throws ParseException{
      
        pessoaEditada.setNome(jNome.getText());
        pessoaEditada.setId(pessoaEmEdicao.getId());
        pessoaEditada.setCpf_cnpj(jCpf_Cnpj.getText());
       pessoaEditada.setTelefone(jTelefone.getText());
       SimpleDateFormat formatter = new SimpleDateFormat("yy-mm-dd");
       java.util.Date dataEsc = jCalendario.getDate();
       String data = formatter.format(dataEsc);
       pessoaEditada.setReclamacao(reclamacaoEditada);
       pessoaEditada.getReclamacao().setData_reclamacao(dataEsc);
       pessoaEditada.getReclamacao().setDescricao(jDescricao.getText());
  
       reclamacaoEditada.setDescricao(jDescricao.getText());
       reclamacaoEditada.setData_reclamacao(dataEsc);
       reclamacaoEditada.setId(Integer.parseInt(idReclama.getText()));
  
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     */
    @SuppressWarnings("unchecked")
    
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioCelular = new javax.swing.JRadioButton();
        jRadioFixo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioCelulaCPF = new javax.swing.JRadioButton();
        jRadioCelulaCNPJ = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jCalendario = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDescricao = new javax.swing.JTextArea();
        salvarModificacao = new javax.swing.JButton();
        jbtnVoltar = new javax.swing.JButton();
        jVar = new javax.swing.JLabel();
        idReclama = new javax.swing.JLabel();
        jTelefone = new javax.swing.JFormattedTextField();
        jCpf_Cnpj = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel2.setBackground(new java.awt.Color(37, 170, 253));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_nome-completo (1).png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_telefone.png"))); // NOI18N

        jRadioCelular.setText("Celular");

        jRadioFixo.setText("Fixo");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_cpf-ou-cnpj.png"))); // NOI18N

        jRadioCelulaCPF.setText("CPF");

        jRadioCelulaCNPJ.setText("CNPJ");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_data-do-atendimento (1).png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_descricao.png"))); // NOI18N

        jDescricao.setColumns(20);
        jDescricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jDescricao.setLineWrap(true);
        jDescricao.setRows(5);
        jScrollPane1.setViewportView(jDescricao);

        salvarModificacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_salvar.png"))); // NOI18N
        salvarModificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarModificacaoActionPerformed(evt);
            }
        });

        jbtnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button_voltar.png"))); // NOI18N
        jbtnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnVoltarMouseClicked(evt);
            }
        });

        jVar.setForeground(new java.awt.Color(255, 255, 255));
        jVar.setText("jLabel7");

        idReclama.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioFixo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioCelulaCPF)
                                .addGap(10, 10, 10)
                                .addComponent(jRadioCelulaCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCpf_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(371, 371, 371)
                                .addComponent(jVar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 938, Short.MAX_VALUE)
                        .addComponent(jbtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(idReclama, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(salvarModificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioFixo)
                                    .addComponent(jRadioCelular))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioCelulaCPF)
                                    .addComponent(jRadioCelulaCNPJ))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCpf_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jVar)
                            .addComponent(idReclama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salvarModificacao)
                    .addComponent(jbtnVoltar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1275, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarModificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarModificacaoActionPerformed
        // TODO add your handling code here:
        
        CadastrarPessoaDAO dao = new CadastrarPessoaDAO();
         try {
              if (jNome.getText().isEmpty() == true || jTelefone.getText().isEmpty() == true || jCpf_Cnpj.getText().isEmpty() == true) {
            JOptionPane optionPane = new JOptionPane();
            String msg = "Preencha todos os Campos";
            optionPane.setMessage(msg);
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog = optionPane.createDialog(null, "ATENÇÃO");
            dialog.setVisible(true);
        }else{
           PesquisaPessoas telaPesquisa = new PesquisaPessoas();
            pegarInfoTela();
       
             dao.alterarPessoa(pessoaEditada);
             dao.alterarReclamacao(reclamacaoEditada);
             telaPesquisa.setVisible(true);
             String msg = "Alteração realizada";
             JOptionPane optionPane = new JOptionPane();
            optionPane.setMessage(msg);
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog = optionPane.createDialog(null, "ATENÇÃO");
            dialog.setVisible(true);
            if(dialog.isShowing()){
            
            telaPesquisa.rodarPesquisa();
            }
             dispose();
         } }catch (Exception ex) {
             Logger.getLogger(ReclamacaoCompleta.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_salvarModificacaoActionPerformed

    private void jbtnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnVoltarMouseClicked
         try {
             // TODO add your handling code here:
             PesquisaPessoas telaPesquisa = new PesquisaPessoas();
            
            telaPesquisa.rodarPesquisa();
            telaPesquisa.setVisible(true);
             dispose();
         } catch (Exception ex) {
             Logger.getLogger(ReclamacaoCompleta.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jbtnVoltarMouseClicked

        private void escolhaCPFouCNPJ() {

        ButtonGroup radioGroup = new ButtonGroup();
        radioGroup.add(jRadioCelulaCPF);
        radioGroup.add(jRadioCelulaCNPJ);
        try {
            CNPJMask = new MaskFormatter("##.###.###/####-##");
            CPFMask = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        jRadioCelulaCPF.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    jCpf_Cnpj.setValue(null);
                    jCpf_Cnpj.setFormatterFactory(new DefaultFormatterFactory(CPFMask));
                }
            }
        });
        jRadioCelulaCNPJ.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    jCpf_Cnpj.setValue(null);
                    jCpf_Cnpj.setFormatterFactory(new DefaultFormatterFactory(CNPJMask));
                }
            }
        });

    }
    
     private void escolhaTelefone() {

        ButtonGroup radioGroup2 = new ButtonGroup();
        radioGroup2.add(jRadioCelular);
        radioGroup2.add(jRadioFixo);
        try {
            celularMask = new MaskFormatter("(##)#####-####");
            fixoMask = new MaskFormatter("(##)####-####");
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        jRadioCelular.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    jTelefone.setValue(null);
                    jTelefone.setFormatterFactory(new DefaultFormatterFactory(celularMask));
                }
                
            }
        });
        jRadioFixo.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    jTelefone.setValue(null);
                   jTelefone.setFormatterFactory(new DefaultFormatterFactory(fixoMask));
                }
            }
        });

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReclamacaoCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReclamacaoCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReclamacaoCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReclamacaoCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ReclamacaoCompleta().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(ReclamacaoCompleta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idReclama;
    private com.toedter.calendar.JDateChooser jCalendario;
    private javax.swing.JFormattedTextField jCpf_Cnpj;
    private javax.swing.JTextArea jDescricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioCelulaCNPJ;
    private javax.swing.JRadioButton jRadioCelulaCPF;
    private javax.swing.JRadioButton jRadioCelular;
    private javax.swing.JRadioButton jRadioFixo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jTelefone;
    private javax.swing.JLabel jVar;
    private javax.swing.JButton jbtnVoltar;
    private javax.swing.JButton salvarModificacao;
    // End of variables declaration//GEN-END:variables
}
